services:
  apprise:
    image: caronc/apprise:latest
    container_name: apprise
    hostname: apprise
    networks:
      - traefik
    ports:
      - 9000:8000
    labels:
      - sqlbak.stop.first=false
      - sqlbak.start.first=true
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.apprise.rule=Host(`apprise.${MY_DOMAIN}`)
      - traefik.http.routers.apprise.entryPoints=websecure
      - traefik.http.routers.apprise.tls=true
      - traefik.http.routers.apprise.tls.certResolver=le
      - traefik.http.routers.apprise.middlewares=basicAuth@docker
      - traefik.http.services.apprise.loadBalancer.server.port=8000
    environment:
      - TZ=America/Sao_Paulo
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - /home/pi/centerMedia/SupportApps/apprise/config:/config
    restart: unless-stopped

networks:
  traefik:
    external: true
    name: traefik
