services:
  tugtainer:
    image: ghcr.io/quenary/tugtainer:latest
    user: "${USER_ID}:${GROUP_ID}"
    container_name: tugtainer
    hostname: tugtainer
    networks:
      - traefik
    ports:
      - 9412:80
    labels:
      - sqlbak.stop.first=true
      - sqlbak.start.first=false
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.tugtainer.rule=Host(`tugtainer.${MY_DOMAIN}`)
      - traefik.http.routers.tugtainer.entryPoints=websecure
      - traefik.http.routers.tugtainer.tls=true
      - traefik.http.routers.tugtainer.tls.certResolver=le
      - traefik.http.routers.tugtainer.middlewares=basicAuth@docker
      - traefik.http.services.tugtainer.loadBalancer.server.port=80
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /home/pi/centerMedia/SupportApps/tugtainer:/tugtainer
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

networks:
  traefik:
    external: true
    name: traefik
