# git.yml
---
- name: Install git
  become: true
  apt:
    pkg:
      - git

- name: Setup editor
  git_config:
    name: core.editor
    scope: global
    value: nano

- name: Setup email
  git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"

- name: Setup name
  git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"

- name: Clone media-server-pi-config repository
  git:
    repo: 'git@github.com:rodrigoma/media-server-pi-config.git'
    dest: "{{ansible_env.HOME}}/media-server-pi-config"
    accept_hostkey: true


# tentar resolver com isso
# https://stackoverflow.com/questions/69201422/ansible-git-clone-github-permission-denied-publickey
# https://ntlx.org/2018/07/use-ansible-to-clone-update-private-git-repositories-via-ssh.html