services:
  pyload-ng:
    image: lscr.io/linuxserver/pyload-ng:arm64v8-latest
    user: "${USER_ID}:${GROUP_ID}"
    container_name: pyload-ng
    hostname: pyload-ng
    networks:
      - traefik
    ports:
      - 8000:8000
    labels:
      - sqlbak.stop.first=true
      - sqlbak.start.first=false
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.pyload-ng.rule=Host(`pyload-ng.${MY_DOMAIN}`)
      - traefik.http.routers.pyload-ng.entryPoints=websecure
      - traefik.http.routers.pyload-ng.tls=true
      - traefik.http.routers.pyload-ng.tls.certResolver=le
      - traefik.http.routers.pyload-ng.middlewares=basicAuth@docker
      - traefik.http.services.pyload-ng.loadBalancer.server.port=8000
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /home/pi/centerMedia/SupportApps/pyload/config:/config
      - /home/pi/downloads/pyload:/downloads
    restart: unless-stopped

networks:
  traefik:
    external: true
    name: traefik
