services:
  portainer-ce:
    image: portainer/portainer-ce:latest
    container_name: portainer-ce
    hostname: portainer-ce
    networks:
      - traefik
    ports:
      - 9000:9000
      - 8000:8000
    labels:
      - sqlbak.stop.first=true
      - sqlbak.start.first=false
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.portainer-ce.rule=Host(`portainer.${USER_DOMAIN}`)
      - traefik.http.routers.portainer-ce.entryPoints=websecure
      - traefik.http.routers.portainer-ce.tls=true
      - traefik.http.routers.portainer-ce.tls.certResolver=le
      - traefik.http.services.portainer-ce.loadBalancer.server.port=9000
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pi/centerMedia/SupportApps/portainer-ce/data:/data
    restart: unless-stopped

networks:
  traefik:
    external: true
    name: traefik
