services:
  traefik:
    image: traefik:latest
    container_name: traefik
    hostname: traefik
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - --api=true
      - --api.insecure=false
      - --api.dashboard=true
      - --api.debug=true
      - --api.disabledashboardad=true
      - --ping=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=true
      - --providers.docker.network=traefik
      - --entryPoints.web.address=:80
      - --entryPoints.web.http.redirections.entryPoint.to=websecure
      - --entryPoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.websecure.address=:443
      - --entryPoints.websecure.http.tls=true
      - --certificatesresolvers.le.acme.dnsChallenge=true
      - --certificatesresolvers.le.acme.dnsChallenge.provider=duckdns
      - --certificatesresolvers.le.acme.dnsChallenge.propagation.delayBeforeChecks=60s
      - --certificatesresolvers.le.acme.email=${USER_EMAIL}
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --log.level=INFO
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.basicAuth.basicauth.users=${TRAEFIK_BASIC_AUTH}
    environment:
      - TZ=America/Sao_Paulo
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
    volumes:
      - /home/pi/centerMedia/SupportApps/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --quiet --tries=1 --spider http://127.0.0.1:8080/ping || exit 1
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 10s

networks:
  traefik:
    name: traefik
